### ISSUE TITLE
Documentation - Creating new OpenAI account and get an API KEY

### ISSUE THREAD

**Issue by iandrosov** [SFDO-Community/grant-content-ai#3]
Document creating new OpenAI account and how to get an API KEY. This can be initially free new account to show user what to expect. (OpenAI account credits do expire even if not used)

**Comment by Abundezt** [comment]
# Creating a New OpenAI Account


## Visit OpenAI Website:
- Go to the OpenAI platform website: [platform.openai.com](https://platform.openai.com).


![Image](https://github.com/SFDO-Community/grant-content-ai/assets/129771593/9f449430-f5b5-4f56-b730-7c5a479ac009)


## Sign Up:
- Click on the 'Sign Up' button.
- Enter your email address and create a password, or use your Google, Microsoft, or Apple account for a quicker sign-up.


![Image](https://github.com/SFDO-Community/grant-content-ai/assets/129771593/8090680c-b539-4997-936a-5efe63ee3572)


## Tell Us About You:
- Fill in your First Name, Last Name, and Birthday.
- Click ‘Agree’ to accept terms and conditions.


## Verification (If you signed up with email and password):
- You will receive a verification email from OpenAI.
- Open the email and click on the verification link to activate your account.


# Obtaining an API Key


## Access API Section:
- Once your account is set up, log in and navigate to the OpenAI dashboard.
- Click on 'API Keys' in the dashboard.

![Image](https://github.com/SFDO-Community/grant-content-ai/assets/129771593/c6897092-00b8-405c-a948-a9bbca7366b6)


## Phone Verification:
- Enter your phone number for verification.
- You will receive a verification code via text message.
- Enter this code in the provided space to verify your phone number.

![Image](https://github.com/SFDO-Community/grant-content-ai/assets/129771593/e003b280-eb1e-4027-8400-0e2eeeaf69e9)

![Image](https://github.com/SFDO-Community/grant-content-ai/assets/129771593/e75bc2a2-7356-4b7d-8f89-b3653866c959)

## Create API Key:
- Look for the option to create a new API key.
- Name your key for easy identification (e.g., 'GranContentKit').
- Click 'Create Secret Key'.


![Image](https://github.com/SFDO-Community/grant-content-ai/assets/129771593/9a1b5906-b808-4e55-814e-a1038bca1d25)


## Copy API Key:
- Your new API key will be displayed on the screen.
- Copy this key and store it securely. It is crucial as it will not be displayed again.
- Consider saving it in a secure note or password manager.


![Image](https://github.com/SFDO-Community/grant-content-ai/assets/129771593/542dea5f-75fa-4697-b6e6-0bd276674c8d)


## Free Account Limitations:
- Start experimenting with $5 in free credit that can be used during your first 3 months. To keep things simple and flexible, pay only for the resources you use. ([Pricing](https://openai.com/pricing))
- Be aware that a free account may have limitations on the number of API calls or access to certain models.
- Review these limitations to understand the scope of your account.


# Notes for Beginners


- **API Key Security**: Treat your API key like a sensitive password. Keep it confidential.
- **Dashboard Familiarization**: Explore the OpenAI dashboard to understand its features.
- **Assistance**: If you're stuck, seek help from online forums, OpenAI support, or knowledgeable friends.
- **Stay Informed**: Monitor OpenAI for feature updates or policy changes.


# Integrating with Salesforce (GCAI Playground)


- **Salesforce External Credential Configuration**: Use your new OpenAI API key to configure the External Credential in Salesforce. This is essential for integrating AI functionalities with Salesforce's LWC (Lightning Web Components).


## Default Model Usage
- **Model Selection**: The GCAI Playground uses the gpt-3.5-turbo-instruct model by default. Note that models like GPT-4 might require a paid account and could lead to Salesforce API callout timeouts.


# Compliance and Disclaimer


- **Responsibility**: Your integration of OpenAI with Salesforce via GCAI Playground must comply with both Salesforce and OpenAI's terms, considering security and compliance aspects.


# Additional Tips


- **Updates and Security**: Regularly check for updates in OpenAI's API and usage policies. Keep your API key secure.
- **Support and Documentation**: For detailed information, refer to OpenAI's official documentation and seek support from community forums or OpenAI's help center.


Following these steps will help you successfully create an OpenAI account and obtain an API key, even if you're a complete beginner with no technical background. Remember, these instructions are designed to guide you through each step with ease and clarity.

**Comment by Abundezt** [comment]
@iandrosov I have added the documentation above. Let me know if it needs any adjustments or if I need to add it anywhere else.
